[package]
name = "rust_hash_cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
opencl3 = "0.12"

# CPU fallback
rayon = "1.8"
md5 = "0.7"
sha1 = "0.10"
sha2 = "0.10"


